package PANTALLAS;
import java.util.HashMap;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class Pantalla_inicio extends javax.swing.JFrame {

     private HashMap<String, String> usuariosRegistrados;
    /**
     * Creates new form Pantalla_inicio
     */
    public Pantalla_inicio() {
       initComponents();
    inicializarUsuarios();
    initListeners(); // ¡MUY IMPORTANTE!
    }
 private void inicializarUsuarios() {
        usuariosRegistrados = new HashMap<>();
        usuariosRegistrados.put("admin", "1234");
        usuariosRegistrados.put("jhostin", "5678");
    }
 private void initListeners() {
        bttn_Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarCredenciales();
            }
        });
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color_fondo = new javax.swing.JPanel();
        imagen1 = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        txt_Contraseña = new javax.swing.JTextField();
        bttn_Iniciar_Sesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Color_fondo.setBackground(new java.awt.Color(0, 36, 120));
        Color_fondo.setForeground(new java.awt.Color(255, 255, 255));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/campomar-logo.jpg"))); // NOI18N

        lbl_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Usuario.setText("Usuario :");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña :");

        txt_Contraseña.setActionCommand("null");

        bttn_Iniciar_Sesion.setText("INICIAR SESION");
        bttn_Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_Iniciar_SesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Color_fondoLayout = new javax.swing.GroupLayout(Color_fondo);
        Color_fondo.setLayout(Color_fondoLayout);
        Color_fondoLayout.setHorizontalGroup(
            Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Color_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Color_fondoLayout.createSequentialGroup()
                        .addComponent(imagen1)
                        .addContainerGap(252, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Color_fondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Usuario)
                            .addComponent(txt_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Color_fondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttn_Iniciar_Sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        Color_fondoLayout.setVerticalGroup(
            Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Color_fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen1)
                .addGap(65, 65, 65)
                .addGroup(Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Usuario)
                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Color_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bttn_Iniciar_Sesion)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Color_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Color_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn_Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_Iniciar_SesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttn_Iniciar_SesionActionPerformed

  private void verificarCredenciales() {
        String usuario = txt_Usuario.getText().trim();
        String contraseña = txt_Contraseña.getText().trim(); // ← Usamos getText()

        if (usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos vacíos", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!usuariosRegistrados.containsKey(usuario)) {
            JOptionPane.showMessageDialog(this, "El usuario no existe.", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!usuariosRegistrados.get(usuario).equals(contraseña)) {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error de autenticación", JOptionPane.ERROR_MESSAGE);
            return;
        }

        abrirSistemaGestionIntegral();
    }
     private void abrirSistemaGestionIntegral() {
        Sistema_Gestion_Integral sistema = new Sistema_Gestion_Integral();
        sistema.setVisible(true);
        sistema.setLocationRelativeTo(null);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Pantalla_inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Color_fondo;
    private javax.swing.JButton bttn_Iniciar_Sesion;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Usuario;
    private javax.swing.JTextField txt_Contraseña;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
